title: Liang,Yi
description: AI & Cognitive Science
site_title: '@cidxb - Yi (Sid) Liang'
# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cidxb
blog_url: www.cidxb.github.io
email: cidxbx@gmail.com
blog_url: https://cidxb.blogspot.com/


# absolute or relative
profile_picture: assets/images/332796019.jpg

# Google Analytics ID
google_analytics: 
