title: Liang,Yi
description: AI Researcher & Independent Developer
site_title: '@cidxb - Yi (Sid) Liang'
# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cidxb
blog_url: www.cidxb.github.io
email: cidxbx@gmail.com


# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
